# image will be published to ghcr.io/<user>/<name>
name: evilwoods-os
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 40 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr:
          /usr # copies config/files/usr into your image's /usr.
          # put configuration files you want in /etc/ on a booted system
          # in /usr/etc/ in the image. read more in files module reference.

  - type: rpm-ostree
    repos:
      # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
    install:
      # - micro
      # - starship
      - tailscale
      - fish
    remove:
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
      - firefox
      - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      # repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      # repo-name: flathub
      # repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
        # - org.mozilla.firefox
        # - org.gnome.Loupe
        # - one.ablaze.floorp//lightning # This is an example of flatpak which has multiple branches in selection (flatpak//branch).
        - app.devsuite.Ptyxis
        - ca.andyholmes.Valent
        - ca.desrt.dconf-editor
        - com.discordapp.Discord
        - com.github.marhkb.Pods
        - com.github.tchx84.Flatseal
        - com.google.Chrome
        - com.mattjakeman.ExtensionManager
        - com.ranfdev.Notify
        - com.valvesoftware.Steam
        - com.visualstudio.code
        - com.vixalien.sticky
        - com.yubico.yubioath
        - de.haeckerfelix.Fragments
        - de.schmidhuberj.Flare
        - dev.serebit.Waycheck
        - io.github.alainm23.planify
        - io.github.fabrialberio.pinapp
        - io.github.shiftey.Desktop
        - io.gitlab.news_flash.NewsFlash
        - io.podman_desktop.PodmanDesktop
        - net.ankiweb.Anki
        - net.nokyan.Resources
        - org.gnome.baobab
        - org.gnome.Calculator
        - org.gnome.Calendar
        - org.gnome.Characters
        - org.gnome.clocks
        - org.gnome.Connections
        - org.gnome.Papers
        - org.gnome.Extensions
        - org.gnome.font-viewer
        - org.gnome.Fractal
        - org.gnome.Loupe
        - org.gnome.Maps
        - org.gnome.NautilusPreviewer
        - org.gnome.Ptyxis.Devel
        - org.gnome.Snapshot
        - org.gnome.TextEditor
        - org.gnome.Todo
        - org.gnome.Weather
        - org.gnome.World.PikaBackup
        - org.libreoffice.LibreOffice
        - org.mozilla.firefox
        - org.standardnotes.standardnotes
        - us.zoom.Zoom

      # Flatpak runtimes are not supported (like org.winehq.Wine//stable-23.08),
      # only normal flatpak applications are (like Floorp Lightning web browser in this example).
      # Installing different branches of the same Flatpak is not supported.
      remove:
      # - org.gnome.eog

  - type: fonts
    fonts:
    nerd-fonts:
      - FiraCode # don't add spaces or "Nerd Font" suffix.
      - Hack
      - SourceCodePro
      - Terminus
      - JetBrainsMono
      - NerdFontsSymbolsOnly

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

